choirpack/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^$', views.home, name="home"),
	url(r'^posts/', include('posts.urls', namespace="posts")),
	url(r'^suggest/$', views.suggestion_view, name='suggestion'),
	url(r'^courses/', include('courses.urls', namespace="courses")),
]

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.course_list, name="course_list"),
	url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/$', views.step_detail, name="step_detail" ),
	url(r'(?P<pk>\d+)/$', views.course_detail, name="course_detail"),
]

posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.post_list, name="post_list"),
	url(r'(?P<slug>\d+)/$', views.post_detail, name="post_detail"),
]

courses/models.py
from django.db import models
#from django.utils.text import slugify

# Create your models here.
class Course(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	title = models.CharField(max_length=255)
	description = models.TextField()
	topic_img = models.ImageField(upload_to='media/topic_img')
	
	def __str__(self):
		return(self.title)
	
class Step(models.Model):
	title = models.CharField(max_length=255)
	description = models.TextField()
	content = models.TextField(blank=True, default='')
	order = models.IntegerField(default=0)
	course = models.ForeignKey(Course)
	
	class Meta:
		ordering = ['order',]
	
	def __str__(self):
		return self.title
	
#	order = models.SlugField()
	
	
#	def save(self, *args, **kwargs):
#		if not self.id:
#			# Newly created object, so set slug
#			self.order = slugify(self.title)
#		super(Step, self).save(*args, **kwargs)

posts/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone


class Post(models.Model):
	STATUS_CHOICES = (
		('draft', 'Draft'),
		('published', 'Published'),
	)
#	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=255)
	description = models.TextField()
	slug = models.SlugField(max_length=100, unique=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	post_img = models.ImageField(upload_to="media/post_img")
	publish = models.DateTimeField(default=timezone.now)
	status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
	
	class Meta:
		ordering = ('-publish',)
	
	def __str__(self):
		return(self.title)
	
#	def slug (self):
#		return slugify(self.title)
#	
##	def save(self, *args, **kwargs):
##		self.slug = slugify(self.title) # set the slug explicitly
##		super(Post, self).save(*args, **kwargs) # call Django's save()
#	
#	def save(self, *args, **kwargs):
#		if not self.id:
#			self.slug = slugify(self.title)
#	
#		super(Post, self).save(*args, **kwargs)

choirpack/forms.py
from django import forms


class SuggestionForm(forms.Form):
	name = forms.CharField()
	email = forms.EmailField()
	suggestion = forms.CharField(widget=forms.Textarea)
	

choirpack/views.py
from django.shortcuts import render
from django.contrib import messages
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

from . import forms


def home(request):
	return render(request, 'home.html')

def suggestion_view(request):
	form = forms.SuggestionForm()
	if request.method == 'POST':
		form = forms.SuggestionForm(request.POST)
		if form.is_valid():
			send_mail(
				'Suggestion from {}'.format(form.cleaned_data['name']),
				form.cleaned_data['suggestion'],
				'{name} <{email}>'.format(**form.cleaned_data),
				['danchuksn@gmail.com']
			)
			messages.add_message(request, messages.SUCCESS, 
							   'Thanks for your suggestion!')
			return HttpResponseRedirect(reverse('suggestion'))
	return render(request, 'suggestion_form.html', {'form': form})

courses/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import Course, Step

# Create your views here.

def course_list(request):
	courses = Course.objects.all()
	email = 'gnwazk@outlook.com'
	return render(request, 'courses/course_list.html', {'courses': courses, 'email': email})

def course_detail(request, pk):
	course = get_object_or_404(Course, pk=pk)
	return render(request, 'courses/course_detail.html', {'course': course})

def step_detail(request, course_pk, step_pk):
	step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
	return render(request, 'courses/step_detail.html', {'step': step})

posts/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from .models import Post

def post_list(request):
	posts = Post.objects.all()
	return render(request, 'posts/post_list.html', {'posts':posts})

def post_detail(request, slug):
	post = get_object_or_404(Post, slug=slug)
	return render(request, 'posts/post_detail.html', {'post':post})

courses/templates/courses/course_detail.html
{% extends "layout.html" %}
{% load humanize %}
{% load course_extras %}


{% block title %}{{course.title}}{% endblock %}


{% block content %}
  <div id="index-banner" class="parallax-container">
	{% include 'navbar.html' %}
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center blue-text text-lighten-2">{{ course.title }} - tutorial page</h1>
        <div class="row center">
          <h5 class="header col s12 light">choose from available topics below to get started</h5>
        </div>
        <div class="row center">
          <a href="#" id="download-button" class="btn-large waves-effect waves-light blue lighten-1">Get Started</a>
        </div>
        <br>

      </div>
    </div>
    <div class="parallax"><img src="{{ course.topic_img.url }}" alt="course background image"></div>
  </div>


     <!--head-page-->

  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>Welcome to {{ course.title }}</h4>
          <p class="center-align light">{{ course.description|markdown_to_html}}
			There are {{ course.step_set.count|apnumber}} step{{ course.step_set.count|pluralize }} in this course: {{ course.step_set.all|join:", " }}</p>
        </div>
      </div>

    </div>
  </div>


    <!--//head-page-->

<!--lists of courses-->
      <div class="container-fluid">
        <div class="row">
          <div class="col s12 m5 l4"> 
          <ul class="collapsible" data-collapsible="accordion">
            <li>
              <div class="collapsible-header">
                <h5>Courses menu <i class="small material-icons circle blue">menu</i></h5>
			  </div>
              <div class="collapsible-body"><span>{% nav_courses_list %}</span>
			 </div>
            </li>
          </ul> 
               <ul class="z-depth-2 collection">
				{% for step in course.step_set.all %}
				<li class="collection-item avatar">
				  <i class="small material-icons circle blue">school</i>
				  <span class="title"><h6>
					  <a href="{% url 'courses:step_detail' course_pk=step.course.pk step_pk=step.pk %}">{{ step.title }}</a></h6></span>
				  <p>{{ step.description }}</p>
				</li>
				{% endfor %}
			  </ul>
	     </div>
	  
	  <div class="col s12 m7 l8">
		 <div class="container">
		  <div class="jumbotron">
			<article>
			 <h3>{{ step.course.title }}</h3>
			 <h4>{{ step.title }}</h4>
			 <p>{{ step.content|linebreaks }}</p>
			</article>
		  </div>
		 </div>
	  </div>
			
    </div><!-- row-->
  </div><!-- container-->

{% endblock %}

courses/templates/courses/course_list.html
{% extends "layout.html" %}
{% load staticfiles %}
{% load humanize %}
{% load course_extras %}

{% block title %}choirpacks | tutorials{% endblock %}

{% block content %}
  <div id="index-banner" class="parallax-container">
	{% include 'navbar.html' %}
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center blue-text text-lighten-2">tutorial page</h1>
        <div class="row center">
          <h5 class="header col s12 light">choose from available topics below to get started</h5>
        </div>
        <div class="row center">
          <a href="#" id="download-button" class="btn-large waves-effect waves-light blue lighten-1">Get Started</a>
        </div>
        <br>

      </div>
    </div>
    <div class="parallax"><img src="{% static 'imgs/writing music 1.jpg' %}" alt="Unsplashed background img 1"></div>
  </div>

<!-- ================================/ tutorial welcome /================================= -->
  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>Welcome to our tutorial Page</h4>
          <p class="left-align light">Welcome to out tutorial page. Are you wasting your valuable time online instead of spending on our site? These online courses will help you make the most out of the time you spend online, aquiring the inspiration and knowledge you need for an effective practice session or enjoyable time learning music.</p>
			<div>
				Dont miss our latest course, 
				<div class="chip">
					 {% newest_course %}
				</div>
			</div>
        </div>
      </div>

    </div>
  </div>

<!-- ===============================/ courses /================================== -->
 <div class="container-fluid">
   <div class="section">
      <!--   Icon Section   -->
      <div class="row">
		  
		{% for course in courses %}
			<div class="col s12 m4">
			  <div class="card">
				<div class="card-image">
				  <img src="{{ course.topic_img.url }}" height = "200" width = "150">
				  <span class="card-title">
					  <a href="{% url 'courses:course_detail' pk=course.pk %}">
						  {{ course.title }}</a></span>
				  <a class="btn-floating halfway-fab waves-effect waves-light blue" 
					  href="{% url 'courses:course_detail' pk=course.pk %}">
					  <i class="material-icons">school</i></a>
				</div>
				<div class="card-content">
					{% if course.description|wordcount <= 5 %}
				  		<p>{{ course.description }}</p>
					{% else %}
				  		<p>{{ course.description|truncatewords:8 }}</p>
						<a href="{% url 'courses:course_detail' pk=course.pk %}">Read more</a>
					{% endif %}
					<div>Created on: {{ course.created_at|date:"F j, Y" }}</div>
				</div><!--card-content-->
			  </div><!--card-->
			</div>
		{% endfor %}

      </div><!-- row -->
      <!--//Icon Section-->
    </div><!-- section -->
  </div><!-- container -->

{% endblock %}

courses/templates/courses/course_nav.html
{% for course in courses %}
  <ul class="collection">
    <li class="collection-item avatar">
      <i class="material-icons circle">school</i>
      <span class="title">
		  <a href="{% url 'courses:course_detail' pk=course.pk %}">{{ course.title }}</a>
	  </span>
      <a href="{% url 'courses:course_detail' pk=course.pk %}" class="secondary-content">
		  <i class="material-icons">grade</i>
	  </a>

    </li><!--collection-item avatar-->
  </ul><!--collection-->

{% endfor %}

courses/templates/courses/step_detail.html
{% extends "layout.html" %}
{% load course_extras %}


{% block title %}{{ step.title }}-{{ step.course.title }}{% endblock %}


{% block content %}
{% include "navbar.html" %}
<br>

      <div class="container-fluid">
        <div class="row">
          <div class="col s12 m5 l4"> 
          <ul class="collapsible" data-collapsible="accordion">
            <li>
              <div class="collapsible-header">
                <h5>Courses menu <i class="material-icons circle">menu</i></h5>
			  </div>
              <div class="collapsible-body"><span>{% nav_courses_list %}</span>
			 </div>
            </li>
          </ul>  
			  <ul class="z-depth-2 collection">
				<li class="collection-item avatar">
				  <span class="title">
				  <h4><a href="{% url 'courses:course_detail' pk=step.course.pk %}">
				  <i class="small material-icons block ">menu</i>
					  {{ step.course.title }}</a></h4></span>
				  <h6>{{ step.title }}</h6>
					{% with cont=step.content %}
					<span class="new badge blue">Content contains: {{ cont|wordcount }} words.
					<br>Estimated time to complete: {{ cont|wordcount|time_estimate }} minute{{ cont|wordcount|time_estimate|pluralize }}</span>
					{% endwith %}
				</li>
			  </ul>
	     </div>
	  
	  <div class="col s12 m7 l8">
		 <div class="container">
			<article>
			 <h3>{{ step.title }}</h3>
			 <h4>{{ step.description }}</h4>
				<br><br>
				{% with con=step.content %}
			    <p>{{ con|linebreaks }}</p>
				{% endwith %}
			</article>
		 </div>
	  </div>
			
    </div><!-- row-->
  </div><!-- container-->
{% endblock %}

courses/templates/courses/step_nav.html
               <ul class="z-depth-2 collection">
				{% for step in course.step_set.all %}
				<li class="collection-item avatar">
				  <i class="small material-icons circle blue">school</i>
				  <span class="title"><h6>
					  <a href="{% url 'courses:step_detail' course_pk=step.course.pk step_pk=step.pk %}">
						  {{ step.title }}</a></h6></span>
				  <p>{{ step.description }}</p>
				</li>
				{% endfor %}
			  </ul>

courses/templates/courses/structure.html
{% extends "layout.html" %}
{% load humanize %}

{% block title %}{{course.title}}{% endblock %}

{% block content %}
<body>
	<div class="row">
      <div class="container">
		  <a href="#" data-activates="nav-mobile" 
			  class="button-collapse top-nav waves-effect waves-light circle hide-on-large-only">
		  <i class="material-icons">menu</i></a></div>
          <ul id="nav-mobile" class="side-nav fixed" data-collapsible="accordion">
<!--<li class="search">
          <div class="search-wrapper card">
            <input id="search"><i class="material-icons">search</i>
            <div class="search-results"></div>
          </div>
        </li>-->

            <li>
              <div class="header">
				  
                <span class="new badge"> {{4}}</span>
                <h5>{{ course.title }}</h5>
			  </div>
              <div class="body"><span>{{ course.description }}</span>
			 </div>
            </li>
		  <div class="row">
		  	<ul class="z-depth-2 collection">
				{% for step in course.step_set.all %}
				<li class="collection-item avatar">
				  <i class="small material-icons circle blue">school</i>
				  <span class="title"><h6>
					  <a href="{% url 'courses:step_detail' course_pk=step.course.pk step_pk=step.pk %}">{{ step.title }}</a></h6></span>
				  <p> {{ step.description }}</p>
				</li>
				{% endfor %}
			  </ul>
		  </div>
      </ul> 
	  
	  <main>
		<div class="container">
		   <h5>{{ step.title }}</h5>
		   <h6>{{ step.description }}</h6>
		   {% with con=step.content %}
		   <span class="new badge">Content: {{ con|wordcount }} words</span>
			<p>{{ con|linebreaks }}</p>
		   {% endwith %}
		</div>  
      </main> 
	</div>
  </body>




    <!-- step detail Page Layout here -->
   
  <div class="content">
   <div class="row">
	   	  <div class="col s12 m5 l4"> 
		 <div class="container">
		 <h4>
		<a href="{% url 'courses:course_detail' pk=step.course.pk %}">
			{{ step.course.title }}</a></h4>
		 <h5>{{ step.title }}</h5>
		 <h6>{{ step.description }}</h6>
		</div>
	     </div>
	  <div class="z-depth-2 col s12 m7 l8">
		  <div class="container">
		   <h5>{{ step.title }}</h5>
		   <h6>{{ step.description }}</h6>
			<br><br>
			  
		   {% with con=step.content %}
			<p>{{ con|linebreaks }}</p>
			<span class="new badge blue">Content contains: {{ con|wordcount }} words. Estimated time to complete: {{ con|wordcount|time_estimate }} minute{{ con|wordcount|time_estimate|pluralize }}</span>
		   {% endwith %}
	  </div>
	</div>

  </div>
 </div>

{% endblock %}




templates/footer.html
{% load staticfiles %}

<!-- ============================// footer //============================= -->
  <footer class="page-footer blue darken-2">
    <div class="container-fluid">
      <div class="row">
        <div class="col l4 s12">
          <h5 class="white-text center"><u>Send us a feed-back</u></h5>
			<form class="col s12">
				<div class="input-field col s12">
				  <i class="material-icons prefix">account_circle</i>
				  <input id="email" type="email" class="validate">
				  <label for="email">Email</label>
				</div>
				<div class="input-field col s12">
				  <i class="material-icons prefix">mode_edit</i>
				  <textarea id="icon_prefix2" class="materialize-textarea"></textarea>
				  <label for="icon_prefix2">Message</label>
				</div>
			  <button class="btn-flat waves-effect waves-light" type="submit" name="action">Submit
				<i class="material-icons right">send</i>
			  </button>
			</form>
		</div>
		  
        <div class="col l3 s12 connect-social">
          <h5 class="white-text center"><u>Connect with us</u></h5>
          <ul> 
			<li><a href="/" class="btn-floating btn-medium waves-effect waves-dark blue  mdi mdi-facebook mdi-24px">facebook</a>  facebook</li>
			<li><a href="/" class="btn-floating btn-medium waves-effect waves-light blue  mdi mdi-twitter mdi-24px">twitter</a>  twitter</li>
			<li><a href="/" class="btn-floating btn-medium waves-effect waves-light red  mdi mdi-google mdi-24px">google</a>  google</li>
			<li><a href="/" class="btn-floating btn-medium waves-effect waves-dark blue  mdi mdi-instagram mdi-24px">instagram</a>  instagram</li>
          </ul>
        </div>
		  
		<div class="col l5 s12">
          <h5 class="white-text center"><u>About us</u></h5>
          <p class="grey-text text-lighten-4">We are a team of music teachers working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by GeeTech Contact us! {{ email|urlize }}
      </div>
    </div>
  </footer>

templates/home.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block title %}choirpacks | home{% endblock %}


{% block content %}
 <!-- ============================================================================= -->

  <div id="index-banner" class="parallax-container">
	  {% include 'navbar.html' %}
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center blue-text text-lighten-2">choirpacks.com</h1>
        <div class="row center">
          <h5 class="header col s12 light">A modern music online tutorial </h5>
        </div>
        <div class="row center">
          <a href="#" id="download-button" class="btn-large waves-effect waves-light blue lighten-1">Get Started</a>
        </div>
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="static/imgs/choir.jpg" alt="Unsplashed background img 1"></div>
  </div>

<!-- =========================================================================== -->
  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>Welcome to choirpacks.com</h4>
          <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
        </div>
      </div>

    </div>
  </div>


<!-- ======================================================================================= -->
  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="static/imgs/classical-music.jpg" alt="Unsplashed background img 2"></div>
  </div>
    
    
<!--================================//article container========================================-->
  <div class="container-fluid">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="flaticon-music-3"></i></h2>
            <h5 class="center">piano basics</h5>

            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="flaticon-violin-2"></i></h2>
            <h5 class="center">violin basics</h5>

            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="flaticon-music-teacher"></i></h2>
            <h5 class="center">music grounded tutorial</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div><!-- row -->
      <!--   Icon Section   -->

    </div><!-- section -->
  </div><!-- container -->  
    
<!-- ====================/ Second container /========================= -->
  <div class="container-fluid">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="flaticon-musical-notation-of-music-class"></i></h2>
            <h5 class="center">piano basics</h5>

            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="flaticon-student-making-a-question-in-class"></i></h2>
            <h5 class="center">violin basics</h5>

            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="flaticon-music"></i></h2>
            <h5 class="center">music grounded tutorial</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div><!-- row -->
      <!--   Icon Section   -->

    </div><!-- section -->
  </div><!-- container -->  
    
    
<!--=============================//=======================================-->
  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="static/imgs/music background.jpg" alt="Unsplashed background img 3"></div>
  </div>
{% endblock %}

templates/layout.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>{% block title %}{% endblock %}</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/materialize.css' %}" type="text/css" media="screen,projection"/>
  <link rel="stylesheet" href="{% static 'css/materialdesignicons.min.css' %}" type="text/css" media="screen,projection"/>
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="screen,projection"/>
  <!-- FLAT ICONS -->
  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}" type="text/css">
</head>
  
<body>
	{% if messages %}
	 <div class='row'>
		 <div class='small-6 small-centered columns'>
			 {% for message in messages %}
			  	 <div data-alert class="alert-box {{message.tags}} radius">
				 {{ message }}
				 <a href="#" class="close">&times;</a>
				 </div>
			 {% endfor %}
		 </div>
	</div>
	{% endif %}

{% block content %}
{% endblock %}

{% include 'footer.html' %}
  <!--  Scripts-->
  <script src="{% static 'js/default.js' %}"></script>
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'js/materialize.js' %}"></script>
  <script src="{% static 'js/init.js' %}"></script>

</body>
</html>

templates/navbar.html
{% load staticfiles %}

   <header>            
    <!-- Dropdown Structure -->
    <ul id='dropdown1' class='dropdown-content'>
      <li><a href="#!"><i class="material-icons left">person add</i>signup</a></li>
      <li><a href="#!"><i class="material-icons left">person</i>login</a></li>
      <li class="divider"></li>
      <li><a href="#!"><i class="material-icons left">person outline</i>logout</a></li>
    </ul>
      
      <nav class="blue darken-1" role="navigation">
        <div class="nav-wrapper container-fluid">
          <a id="logo-container" href="{% url 'home' %}" class="brand-logo">choirpacks</a>
          <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'home' %}"><i class="material-icons left">home</i>home</a></li>
            <li><a href="{% url 'courses:course_list'%}"><i class="material-icons left">school</i>tutorials</a></li>
            <li><a href="#"><i class="material-icons left">group</i>community</a></li>
            <li><a href="#"><i class="material-icons left">archive</i>archives</a></li>
            <li>
                <!-- Dropdown Trigger -->
              <a class="dropdown-button" href="#!" data-activates="dropdown1">account
                <i class="material-icons right">arrow_drop_down</i></a>
            </li>
            <form class="left">
              <div class="input-field">
                <input id="search" type="search" />
                <label for="search"><i class="material-icons">search</i></label>
                <i class="material-icons">close</i>
              </div>
            </form>
          </ul>


          <ul id="nav-mobile" class="side-nav">
          <ul class="right hide-on-med-and-down">
          </ul>
            <li><a href="{% url 'home' %}">home</a></li>
            <li><a href="{% url 'courses:course_list'%}">tutorials</a></li>
            <li><a href="#">community</a></li>
            <li><a href="#">downloads</a></li>
            <li><a href="#">login</a></li>
            <li><a href="#">signup</a></li>
             <form class="left">
              <div class="input-field">
                <input id="search" type="search" />
                <label for="search"><i class="material-icons">search</i></label>
                <i class="material-icons">close</i>
              </div>
            </form>
          </ul>
          <a href="#" data-activates="nav-mobile" class="button-collapse">
          <span class="material-icons">menu</span></a>
        </div>
      </nav>
    </header>

templates/suggestion_form.html
{% extends "layout.html" %}

{% block title %}{% endblock %}

{% block content %}
{% include 'navbar.html' %}
<div class='row'>
	 <div class='content'>
			<h4 class="center-align">Welcome! to our suggestion page</h4>
			<hr width='20%'>
				 <form action='' method='POST'>
					 {{form.as_p}}
					 {% csrf_token %}
					 <button class="btn-flat waves-effect waves-light" type="submit" name="action">Submit
						<i class="material-icons right">send</i>
					 </button>
				 </form>
	 </div>
</div>
{% endblock %}